name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Install SQLx CLI (for migrations)
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Setup Postgres
        uses: Harmon758/postgresql-action@v1
        with:
          postgresql version: '15'
          postgresql db: pulsewatch
          postgresql user: pulse
          postgresql password: pulse

      - name: Run migrations
        run: just migrate

      - name: Check formatting
        run: just fmt -- --check

      - name: Lint
        run: just lint

      - name: Run tests
        run: just test
